export enum Status {
  BACKLOG = 'BACKLOG',
  UNDER_STUDY = 'UNDER_STUDY',
  PROPOSAL = 'PROPOSAL',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_VALIDATION = 'IN_VALIDATION',
  DONE = 'DONE',
  CANCELED = 'CANCELED',
}
